name: Caller Workflow

on: 
  push:
    branches:
      - main

jobs:
  trigger-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Call Workflow Template
      uses: actions/github-script@v6
      with:
        script: |
          github.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: '.github/workflow-templates/workflow-template.yml',
            ref: 'main',
            inputs: {
              dockerhub_username: 'secrets.DOCKERHUB_USERNAME',
              dockerhub_token: '${{ secrets.DOCKERHUB_TOKEN }}',
            }
          })
        secrets: 'inherit'
