name: Caller Workflow

on: 
  push:
    branches:
      - main

jobs:
  trigger-workflow-dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      workflows: write
    steps:
    - name: Dispatch Workflow
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'workflow.yml', # Make sure this is the correct path within .github/workflows/
            ref: 'main',
            inputs: {
              dockerhub_username: '${{ secrets.DOCKERHUB_USERNAME }}',
              dockerhub_token: '${{ secrets.DOCKERHUB_TOKEN }}',
            }
          });
